### ISSUE TITLE
Latest release (2023-04-13) causes blurry textures

### ISSUE THREAD

**Issue by EternalHabit** [GhostlyDark/MM-Reloaded#1]
![Screenshot 2023-04-18 202044](https://user-images.githubusercontent.com/30607392/232935227-bcd9848b-aa73-42fa-a3b1-0b470b9fc14c.png)

MMHD-MLE release version 2022-01-29 didn't have this problem. I've tested both textures packs with GhostlyDark GLideN64 version 2023-04-13. Project64 version in photo. (if trying to replicate bug)

**Comment by GhostlyDark** [comment]
Toogle `inaccurate texture coordinates`.
