### ISSUE TITLE
[REQUEST] 2ship2harkinian support?

### ISSUE THREAD

**Issue by AwayCoast23465** [GhostlyDark/MM-Reloaded#2]
is this planned/possible to be done? sorry if it is too close to release, as it was only released a small while ago

**Comment by Horonelius** [comment]
Eagerly awaiting this.

**Comment by valkyrie743** [comment]
also would love this for 2ship.

**Comment by GhostlyDark** [comment]
WIP is available here:
https://github.com/GhostlyDark/MM-Reloaded-2S2H

There are no release files however, until the blocking issues are resolved (by the 2Ship devs, not me):
https://github.com/GhostlyDark/MM-Reloaded-2S2H/issues/1

Once 2Ship is ready, the pack can be prepared for a release, which is then going to be available here:
https://github.com/GhostlyDark/MM-Reloaded-2S2H/releases/latest

No ETA on any of this, as that mostly depends on the volunteers that are contributing to the 2ship2harkinian project.
